apiVersion: v1
kind: PersistentVolume
metadata:
  name: midlink-task-pv
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/var/midlink-task"
  storageClassName: ""
