apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: midlink-task-pvc
spec:
  accessModes:
    - ReadWriteMany
  volumeMode: Filesystem
  resources:
    requests:
      storage: 5Gi
  storageClassName: ""
